### ISSUE TITLE
Fix: App is crashing when try to change the status bar color programatically

### ISSUE THREAD

**Issue by kaungkhantsoe** [nimblehq/jetpack-compose-ecommerce#36]
## Issue

App is crashing with the following error as soon as it is launched.

![Screen Shot 2022-05-19 at 1 10 18 PM (2)](https://user-images.githubusercontent.com/32578035/169223517-1ca079e6-54d5-4a36-ad00-f418e02cc02c.png)

## Environment

Device 1
- Device: Samsung Galaxy S10+
- OS: Android 11

Device 2
- Device: Mi 9
- OS: Android 11

## Expected

App should not crash.
 
## Steps to reproduce

Run application.

**Comment by hoangnguyen92dn** [comment]
@kaungkhantsoe Can you please add device-specific such as Model, and OS version 😄

**Comment by kaungkhantsoe** [comment]
> @kaungkhantsoe Can you please add device-specific such as Model, and OS version 😄

@hoangnguyen92dn Updated 🙏
